#!/usr/bin/env node
"use strict";

// Schedule future-dated posts for automatic publishing.
//
// The site is gated at build time: `.eleventy.js` only emits a post once
// `item.date <= new Date()` (in production). So a post dated in the future is
// silently held back until *some* build runs at-or-after its date. Nothing
// rebuilds the site on its own, so without help a scheduled post never appears
// at its time — it waits for the next unrelated push to main.
//
// This script closes that gap *without* a polling cron that wakes up when there
// is nothing to do. Instead it derives the schedule from the posts themselves:
// it writes one exact-minute `cron` entry into `.github/workflows/
// scheduled-publish.yml` per pending future post. When no future posts exist,
// the `schedule:` trigger is removed entirely, so that workflow never fires on a
// timer. GitHub cron is UTC and minute-granular, which is exactly what we emit.
//
// Commands:
//   arm     Regenerate the managed schedule block + state file from the posts.
//           Run after each successful production deploy via arm-schedule.yml.
//           Idempotent: identical inputs produce identical files, so it never
//           creates empty commits.
//   status  Print the upcoming scheduled publishes (no file changes).

const fs = require("fs");
const path = require("path");
const matter = require("gray-matter");

const root = process.cwd();
const postsRoot = path.join(root, "blog/posts");
const workflowFile = path.join(root, ".github/workflows/scheduled-publish.yml");
const stateFile = path.join(root, ".github/scheduled-publish-state.json");

const SCHEDULE_START =
  "  # === managed-schedule START (generated by scripts/schedule-publish.js — do not edit) ===";
const SCHEDULE_END = "  # === managed-schedule END ===";

function listMarkdownFiles(dir) {
  if (!fs.existsSync(dir)) return [];

  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listMarkdownFiles(full));
    else if (entry.isFile() && full.endsWith(".md")) out.push(full);
  }
  return out;
}

function isTruthy(value) {
  if (typeof value === "boolean") return value;
  return ["true", "1", "yes"].includes(String(value || "").toLowerCase());
}

// Mirrors the slug/date/draft conventions used in scripts/lib/publish-utils.js.
function parsePost(file) {
  const data = matter(fs.readFileSync(file, "utf8")).data || {};
  const date = data.date ? new Date(data.date) : null;
  if (!date || Number.isNaN(date.getTime())) return null;

  const slug =
    data.slug || path.basename(file, ".md").replace(/^\d{4}-\d{2}-\d{2}-/, "");

  return { slug, date, draft: isTruthy(data.draft) };
}

// All non-draft posts whose date is still in the future, earliest first. The
// slug tiebreaker keeps the order deterministic for posts that share a date, so
// the generated block (and state file) don't churn across machines where
// readdir order differs (local vs CI).
function pendingPosts(now) {
  return listMarkdownFiles(postsRoot)
    .map(parsePost)
    .filter((post) => post && !post.draft && post.date > now)
    .sort((a, b) => a.date - b.date || a.slug.localeCompare(b.slug));
}

// GitHub Actions cron: "minute hour day-of-month month day-of-week", in UTC.
// Day-of-week is left as "*". There is no year field, so an entry matches the
// same calendar day every year — harmless here because entries are removed as
// soon as the post is published (and re-armed only while still in the future).
function toCron(date) {
  return [
    date.getUTCMinutes(),
    date.getUTCHours(),
    date.getUTCDate(),
    date.getUTCMonth() + 1,
    "*"
  ].join(" ");
}

// Build the managed `on:` block. One cron per distinct UTC minute; posts that
// share a minute are listed together in the trailing comment.
function buildScheduleBlock(posts) {
  if (posts.length === 0) {
    return [
      SCHEDULE_START,
      "  # No scheduled publishes pending — this workflow has no timer trigger.",
      SCHEDULE_END
    ].join("\n");
  }

  const byCron = new Map();
  for (const post of posts) {
    const cron = toCron(post.date);
    if (!byCron.has(cron)) byCron.set(cron, []);
    byCron.get(cron).push(post);
  }

  const lines = [SCHEDULE_START, "  schedule:"];
  for (const [cron, group] of byCron) {
    const label = group
      // Collapse any whitespace in the slug so the trailing YAML comment can
      // never wrap onto a second line and break the block.
      .map((p) => `${p.date.toISOString()} · ${String(p.slug).replace(/\s+/g, " ")}`)
      .join(", ");
    lines.push(`    - cron: "${cron}" # ${label}`);
  }
  lines.push(SCHEDULE_END);
  return lines.join("\n");
}

function replaceManagedBlock(content, block) {
  const start = content.indexOf(SCHEDULE_START);
  const endMarker = content.indexOf(SCHEDULE_END);
  if (start === -1 || endMarker === -1) {
    throw new Error(
      `Managed-schedule markers not found in ${path.relative(root, workflowFile)}`
    );
  }
  // Refuse to operate on a file with duplicated markers — replacing between the
  // first START and first END would orphan the second pair and corrupt the YAML.
  if (
    content.indexOf(SCHEDULE_START) !== content.lastIndexOf(SCHEDULE_START) ||
    content.indexOf(SCHEDULE_END) !== content.lastIndexOf(SCHEDULE_END)
  ) {
    throw new Error(
      `Duplicated managed-schedule markers in ${path.relative(root, workflowFile)} — refusing to edit.`
    );
  }
  if (endMarker < start) {
    throw new Error(
      `Managed-schedule END precedes START in ${path.relative(root, workflowFile)} — refusing to edit.`
    );
  }
  const end = endMarker + SCHEDULE_END.length;
  return content.slice(0, start) + block + content.slice(end);
}

function arm(now) {
  const posts = pendingPosts(now);

  const current = fs.readFileSync(workflowFile, "utf8");
  const updated = replaceManagedBlock(current, buildScheduleBlock(posts));
  if (updated !== current) fs.writeFileSync(workflowFile, updated);

  const state = {
    updatedAt: now.toISOString(),
    pending: posts.map((p) => ({
      slug: p.slug,
      date: p.date.toISOString(),
      cron: toCron(p.date)
    }))
  };
  const serialized = `${JSON.stringify(state, null, 2)}\n`;
  const previous = fs.existsSync(stateFile)
    ? fs.readFileSync(stateFile, "utf8")
    : "";
  // Keep updatedAt out of the change check so an unchanged schedule does not
  // churn a commit on every run. A corrupt or older-format state file parses to
  // "" here, which differs from any real pending list, so we simply rewrite it.
  let previousPending = "";
  try {
    if (previous) previousPending = JSON.stringify(JSON.parse(previous).pending);
  } catch {
    previousPending = "";
  }
  if (JSON.stringify(state.pending) !== previousPending) {
    fs.writeFileSync(stateFile, serialized);
  }

  if (posts.length === 0) {
    console.log("No future-dated posts — schedule cleared.");
  } else {
    console.log(`Armed ${posts.length} scheduled publish(es):`);
    for (const post of posts) {
      console.log(`  ${post.date.toISOString()}  ${post.slug}  (cron: ${toCron(post.date)} UTC)`);
    }
  }
}

function status(now) {
  const posts = pendingPosts(now);
  if (posts.length === 0) {
    console.log("No scheduled publishes pending.");
    return;
  }
  console.log("Upcoming scheduled publishes:");
  for (const post of posts) {
    console.log(`  ${post.date.toISOString()}  ${post.slug}`);
  }
}

function main() {
  const command = process.argv[2] || "arm";
  const now = new Date();

  if (command === "arm") arm(now);
  else if (command === "status") status(now);
  else {
    console.error(`Unknown command: ${command} (expected "arm" or "status")`);
    process.exit(1);
  }
}

main();
