import { tokenKey } from "./00-konstanten.js";

import { els } from "./01b-elements.js";

export const runtimeAssets = document.getElementById("adminRuntimeAssets")?.dataset || {};

export const fieldLabels = {
  slug: els.slugInput.closest("label"),
  permalink: els.permalinkInput.closest("label"),
  date: els.dateInput.closest("label")
};

export const state = {
  token: sessionStorage.getItem(tokenKey) || "",
  tokenAuthorizationError: "",
  session: { authenticated: false, authorized: false, configured: false },
  collection: "posts",
  view: "library",
  tree: null,
  treeHeadSha: "",
  treeParentHeadSha: "",
  mainTree: null,
  mainTreeHeadSha: "",
  changeCache: null,
  startupSnapshotActive: false,
  refreshPromise: null,
  entries: [],
  media: [],
  mediaManifest: null,
  mediaManifestBase: null,
  mediaManifestBaseSha: "",
  mediaManifestRecords: new Map(),
  mediaManifestSignature: "",
  entryLookup: new Map(),
  searchIndex: new Map(),
  searchIndexStatus: "idle",
  searchIndexPromise: null,
  searchIndexRequest: 0,
  searchPendingTexts: new Map(),
  changes: new Map(),
  // Abgewählt statt ausgewählt: Was neu in die Warteschlange kommt, ist damit von selbst dabei.
  // Andersherum müsste jede neue Änderung erst angehakt werden, und wer das übersieht, sendet
  // weniger als er glaubt — der leisere und deshalb schlimmere Fehler.
  queueAbgewaehlt: new Set(),
  current: null,
  autoSlug: false,
  bodyMarkdown: "",
  savedSnapshot: "",
  autosaveSnapshot: "",
  autosaveTimer: null,
  suppressRestore: false,
  editor: null,
  editorRuntimePromise: null,
  previewRuntimePromise: null,
  editorMode: "markdown",
  editorDragDepth: 0,
  pullSettleTimer: null,
  isBusy: false,
  publishInFlight: false,
  publishRequest: null,
  publishStatus: null,
  publishStartedCount: 0,
  publishStartedSignatures: new Set(),
  publishAnnouncementKey: "",
  publishPollToken: 0,
  publishPollController: null,
  queueRefreshRequest: 0,
  navigating: false,
  mediaReferenceIndex: new Map(),
  mediaReferenceSignature: "",
  mediaReferenceRequest: 0,
  mediaProcessing: false,
  mediaCommitPromise: null,
  mediaProcessingPromise: null,
  mediaRecoveryPromise: null,
  mediaActiveJobs: 0,
  mediaRecoveryJobs: 0,
  pendingMediaUploads: new Map(),
  failedMediaUploads: new Map(),
  mediaUploadItems: new Map(),
  mediaFailureRecoveryPromise: null,
  renameOrigins: {},
  renameOriginsLoadedSha: null,
  socialImagePick: null,
  postsIndex: null,
  postsIndexPromise: null,
  socialConfig: null,
  socialConfigSha: "",
  socialConfigPromise: null,
  socialConfigDraft: null,
  socialConfigLoaded: "",
  statsPeriod: { preset: "7d", from: "", to: "" },
  statsRequest: 0,
  statsCache: new Map(),
  statsPromises: new Map(),
  statsControllers: new Map(),
  statusTimer: null,
  startRetryTimer: null
};

export const isMobile = () => window.matchMedia("(max-width: 52rem)").matches;
